import Foundation

struct SOAPNote: Codable, Identifiable {
    var id = UUID()
    let generatedDate: Date
    let periodStart: Date
    let periodEnd: Date
    let subjective: String
    let objective: String
    let assessment: String
    let plan: String
    let medicalSourcesUsed: [String]

    var formattedPeriod: String {
        let f = DateFormatter()
        f.dateStyle = .medium
        return "\(f.string(from: periodStart)) — \(f.string(from: periodEnd))"
    }

    var formattedDate: String {
        let f = DateFormatter()
        f.dateStyle = .long
        f.timeStyle = .short
        return f.string(from: generatedDate)
    }

    var exportText: String {
        """
        CLINICAL SOAP NOTE — Generated by Aura
        Patient Health Diary Report
        Period: \(formattedPeriod)
        Generated: \(formattedDate)
        
        ═══════════════════════════════════════
        S — SUBJECTIVE
        ═══════════════════════════════════════
        \(subjective)
        
        ═══════════════════════════════════════
        O — OBJECTIVE
        ═══════════════════════════════════════
        \(objective)
        
        ═══════════════════════════════════════
        A — ASSESSMENT
        ═══════════════════════════════════════
        \(assessment)
        
        ═══════════════════════════════════════
        P — PLAN
        ═══════════════════════════════════════
        \(plan)
        
        ───────────────────────────────────────
        Medical Sources: \(medicalSourcesUsed.joined(separator: ", "))
        
        DISCLAIMER: This report is AI-generated from patient self-reported data
        and cross-referenced with FDA FAERS and NLM MedlinePlus databases.
        It is not a substitute for professional clinical evaluation.
        Generated by Aura — AI Health Diary (MIT Hackathon 2026)
        """
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = UUID()
        generatedDate = Date()
        periodStart = (try? c.decode(Date.self, forKey: .periodStart)) ?? Date()
        periodEnd = (try? c.decode(Date.self, forKey: .periodEnd)) ?? Date()
        subjective = (try? c.decode(String.self, forKey: .subjective)) ?? ""
        objective = (try? c.decode(String.self, forKey: .objective)) ?? ""
        assessment = (try? c.decode(String.self, forKey: .assessment)) ?? ""
        plan = (try? c.decode(String.self, forKey: .plan)) ?? ""
        medicalSourcesUsed = (try? c.decode([String].self, forKey: .medicalSourcesUsed)) ?? []
    }

    init(
        generatedDate: Date = Date(),
        periodStart: Date,
        periodEnd: Date,
        subjective: String,
        objective: String,
        assessment: String,
        plan: String,
        medicalSourcesUsed: [String] = []
    ) {
        self.id = UUID()
        self.generatedDate = generatedDate
        self.periodStart = periodStart
        self.periodEnd = periodEnd
        self.subjective = subjective
        self.objective = objective
        self.assessment = assessment
        self.plan = plan
        self.medicalSourcesUsed = medicalSourcesUsed
    }

    private enum CodingKeys: String, CodingKey {
        case periodStart, periodEnd, subjective, objective, assessment, plan, medicalSourcesUsed
    }
}
